* - (a) reading gym data set;
data GYM;
    infile 'Z:/Lab1/gym.dat';
    input ID Gender $ Age Weight;
run;
* - (b) use proc contents to print db view;
proc contents data=GYM;
run;
proc print data=GYM;
run;
* - (c) create 'MALE_GYM' only males subset and double check via print;
data MALE_GYM;
	set GYM;
	where Gender='M';
run;
proc contents data=MALE_GYM;
run;
proc print data=MALE_GYM;
run;
* - (d) create 'OLDER_F' subset females >= 10 yrs of age and double check via print;
data OLDER_F;
	set GYM;
	where Gender = 'F' and Age >= 10;
run;
proc contents data=OLDER_F;
run;
proc print data=OLDER_F;
run;
