* - Create 'YEAR1996' from 'data96.dat';
data YEAR1996;
	infile 'Z:/Lab1/DATA96.DAT';
	input ID Height Weight;
run;
* - Create 'YEAR1997' from 'data97.dat';
data YEAR1997;
	infile 'Z:/Lab1/DATA97.DAT';
	input ID Height Weight;
run;
* - Print and view db for both data sets;
proc contents data=YEAR1996;
run;
proc print data=YEAR1996;
run;
proc contents data=YEAR1997;
run;
proc print data=YEAR1997;
run;
* - Merge datasets into 'BOTH' then print to view merged dataset;
data BOTH;
	set YEAR1996 YEAR1997;	
run;
proc sort data=BOTH;
	by ID;
run;
data _null_;
	* - Write output file;
	file 'Z:/Lab1/BOTH.DAT';
	set BOTH;
	put ID Height Weight;
	file close;
run;

proc contents data=BOTH;
run;
proc print data=BOTH;
run;
