* HW 5 
Question D1;
libname mydata 'Z:\';
* Add in dataframe;
data icv;
	set mydata.icvmodeltrain_281;
run;
proc corr data=icv;
	var distfwy distfwy2 distmajorroad logtrafficvol logtrafficvol2 elevationmean elevationsd popdensity;
run;
*Question D2 - build a model to predict NO2;
proc reg data=icv;
	model no2=distfwy distfwy2 distmajorroad logtrafficvol logtrafficvol2 elevationmean elevationsd popdensity/selection=rsquare cp;
run;
proc reg data=icv;
	title'Regression NO2 on log(Traffic Volume), Elevation Mean, and Population Density';
	model no2=logtrafficvol elevationmean popdensity;
	output out=QD2 r=residuals p=predictions rstudent=jackknife;
run;
*Question D3 - Check regression assumptions/use prior output;
proc univariate data=QD2 plot normal;
	title'Check for Normality';
	var residuals;
run;
*Question D4 - plot jackknife vs predicted;
proc sgplot data=QD2;
	title'Scatter plot of Jackknife versus Predicted NO2 Values';
	scatter y=jackknife x=predictions;
	refline 0;
run;
