* HW 5 
Question A1;
libname mydata 'Z:\';
* Add in dataframe from HW2;
data sbp;
	infile 'Z:\ex0502_281.dat' expandtabs;
	input person sbp quet age smk;
	bmi = quet/100*703.1;
	label sbp='Systolic blood pressure (mmhg)';
	label quet='Quetlet index (100 x weight/height^2)';
	label smk='Current or previous smoker';
	label age='Age (years)';
	label bmi='Body mass index (kg/m2)';
run;
* Create Regression model;
proc reg data=sbp;
	model sbp=bmi/r influence;
	output out=QA1 r=resid student=studentized rstudent=jackknife p=pred;
	title 'Regression SBP on BMI';
run;
* Question A2;
* residuals vs. predicted values;
proc sgplot data=QA1;
	scatter y=resid x=pred;
	refline 0;
	title 'Normal Residuals versus Predicted Values';
run;
* studentized vs. predicted values;
proc sgplot data=QA1;
	scatter y=studentized x=pred;
	refline 0;
	title 'Studentized Residuals versus Predicted Values';
run;
* jackknife vs. predicted values;
proc sgplot data=QA1;
	scatter y=jackknife x=pred;
	refline 0;
	title 'Jackknife Residuals versus Predicted Values';
run;
* Question A3;
proc univariate data=QA1;
	var resid studentized jackknife;
	id  resid studentized jackknife;
run;
* Calculate p-value's;
data QA3;
	t1=-2.268082; * Observation 12 - Jackknife Outlier Low;
	t2=2.78039; * Observation 9 - Jackknife Outlier High;
	n=32;
	df=n-1-2;
	pval_Jackknife12=(1-probt(abs(t1),df))*2; * Low Residual;
	pval_Jackknife9=(1-probt(abs(t2),df))*2; * High Residual;
	alpha_adj=0.05/n; * Adjusted alpha level of significance corrected for multiple comparisons;
run;
proc print data=QA3;
	title'Computing P-value for 12th/9th observation JackKnife Residual';
run; 
	
