* HW 5 
Question C1;
libname mydata 'Z:\';
* Add in dataframe from HW2;
data sbp;
	infile 'Z:\ex0502_281.dat' expandtabs;
	input person sbp quet age smk;
	bmi = quet/100*703.1;
	label sbp='Systolic blood pressure (mmhg)';
	label quet='Quetlet index (100 x weight/height^2)';
	label smk='Current or previous smoker';
	label age='Age (years)';
	label bmi='Body mass index (kg/m2)';
run;
proc reg data=sbp;
	title 'Regression SBP on AGE, BMI, and SMK';
	model sbp= age bmi smk/selection=rsquare cp;
	output out=reg_out p=predicted_values r=residuals;
run;
*Question C2 - backward approach;
proc glmselect data=sbp;
	model sbp=age bmi smk/selection=backward sls=0.05 details=all hierarchy=single showpvalues select=sl stop=sl;
run;
*Question C3 - forward approach;
proc glmselect data=sbp;
	model sbp=age bmi smk/selection=forward sle=0.05 details=all hierarchy= single showpvalues select=sl stop=sl;
run;
*Question C4 - stepwise approach;
proc glmselect data=sbp;
	model sbp=age bmi smk/selection=stepwise sle=0.05 sls=0.05 details=all hierarchy= single showpvalues select=sl stop=sl;
run;
*Question C5 - Test interactions with forward selection approach;
proc glmselect data=sbp;
	model sbp=age bmi smk age*bmi age*smk bmi*smk age*bmi*smk/selection=forward sle=0.15 details=all hierarchy= single showpvalues select=sl stop=sl;
run;
*Question C6;
*add in multiplicative interaction term var to dataframe;
data sbp;
	set sbp;
	agebmi=age*bmi;
run;
* sort the data by smoking status;
proc sort data=sbp;
	by smk;
run;
proc reg data=sbp; *Run regression via best subsets approach;
	by smk;
	model sbp=age bmi agebmi/selection=rsquare cp;
run;
data nosmoke; *df non-smokers;
	set sbp;
	if smk=0; *condition to add non-smokers;
run;
data smoke; *df smokers;
	set sbp;
	if smk=1; *condition to add smokers;
run;
proc reg data=nosmoke; 
	title'Nonsmokers: Regression SBP on Age BMI Age*BMI';
	model sbp=age bmi;
	model sbp=age bmi agebmi;
run;
proc reg data=smoke;
	title'Smokers: Regression SBP on Age BMI Age*BMI';
	model sbp=age;
	model sbp=age bmi agebmi;
run;
