* - HW #3 Question B 1.;
libname mydata 'Z:/';

data chol_281;
	set mydata.chol_281;
	logTG = log(tg);
run;
* logTG vs Sex;
proc sgplot data=chol_281;
	scatter y=logTG x=Female;
	reg y=logTG x=Female;
	title 'logTG vs Sex';
run;
* logTG vs BMI;
proc sgplot data=chol_281;
	scatter y=logTG x=BMI;
	reg y=logTG x=BMI;
	title 'logTG vs BMI';
run;
* logTG vs Age;
proc sgplot data=chol_281;
	scatter y=logTG x=Age;
	reg y=logTG x=Age;
	title 'logTG vs Age';
run;
* logTG vs Height;
proc sgplot data=chol_281;
	scatter y=logTG x=ht;
	reg y=logTG x=ht;
	title 'logTG vs Height';
run;
