* - HW #3 Question C 3.;
libname mydata 'Z:/';
* redefine active df for clarity;
data HW3_C3;
	set HW3_C1;
run;
proc glm data=HW3_C3;
	class quartile sex race;
	model FEV=Height Quartile Sex Race/solution clparm;
	title 'Multiple Linear Regression REV on Weight(Quartiles), Height, Sex, and Race';
	output out=mlrFEV r=residuals p=predictions;
run;
proc sgplot data=mlrFEV;
	scatter y=residuals x=predictions;
	refline 0/axis=y;
	title 'Scatter plot of predictions vs residuals';
run;
proc univariate data=mlrFEV normal plot;
	var residuals;
	title 'Test for Normality';
run; 
