* - HW #3 Question C 2.;
libname mydata 'Z:/';

proc format;
  value SEXF 1='Male' 2='Female';
  value RACEF 1='asian' 2='african american' 3='hispanic' 4='non-hispanic' 5='other';
run;
data HW3_C1;
	set mydata.subjdata_281;
run;
proc print data=HW3_C1;
run;
* - Get quartile data parameters for weight;
proc univariate data=HW3_C1;
	var weight;
run; * - 1/2/3 Quartiles were 66/76/88 respectively;

*redefine df with quartiles;
data HW3_C1;
	set HW3_C1;
	if weight ne . then do;
	if weight<66 then quartile ='1';
		else if 66<=weight<76 then quartile='2';
		else if 76<=weight<88 then quartile='3';
		else if weight >=88 then quartile='4';
	end;
run;
proc freq data=HW3_C1;
	tables weight*quartile / norow nocol nopercent missing;
run;

proc freq data=HW3_C1;
	table quartile race sex;
	title 'Categorical Variable Summary Stats (Quartile, Race, and Sex)';
run;
proc means data=HW3_C1;
	var FEV Height;
	title 'Continuous Variable Summary Stats (FEV and Height)';	
run;
*- Reg FEV and Weight Quartiles;
proc glm data=HW3_C1;
	class Quartile;
	model FEV=Quartile/solution;
	title 'Reg FEV on Weight(Quartile)';
run;
*- Reg FEV and Race;
proc glm data=HW3_C1;
	class Race;
	model FEV=Race/solution;
	title 'Reg FEV on Race';
run;
*- Reg FEV and Sex;
proc glm data=HW3_C1;
	class Sex;
	model FEV=Sex/solution;
	title 'Reg FEV on Sex';
run;
*- Reg FEV and Height;
proc glm data=HW3_C1;
	class Height;
	model FEV=Height/solution;
	title 'Reg FEV on Height';
run;
